# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Digital Foster
email: pif@pif.gov
description: > # this means to ignore newlines until "baseurl:"
  A collection of tools available to foster youth, families, and providers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://digitalfoster.org" # the base hostname & protocol for your site
twitter_username: InnovFellows
github_username: digital-foster
repo: https://github.com/digital-foster/digitalfoster

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md

permalink: /:path/

collections:
  products:
    output: true
    permalink: /products/:path/
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: products
    values:
      layout: product
  - scope:
      path: ""
      type: projects
    values:
      layout: project
